version: '3'

services:
  librepass:
    image: medzik/librepass
    build:
      dockerfile: './Dockerfile'

    env_file:
      - .env

    ports:
      - "80:8080"

    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'

    volumes:
      - ./db-data:/var/lib/postgresql/data:Z

    env_file:
      - '.env'
