version: '3'

services:
  librepass:
    image: medzik/librepass

    env_file:
      - .env

    volumes:
      - ./privateKey.pem:/app/privateKey.pem:Z
      - ./publicKey.pem:/app/publicKey.pem:Z
      - ./ssl-keystore.p12:/app/ssl-keystore.p12:Z

    ports:
      - "80:8080"
      - "443:8443"

    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'

    volumes:
      - ./db-data:/var/lib/postgresql/data:Z

    env_file:
      - '.env'
