version: '3'

services:
  librepass:
    image: medzik/librepass
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - librepass-db
    env_file:
      - .env
    volumes:
      - ./logs:/logs:Z
    ports:
      - "8080:8080"

    depends_on:
      - postgres

  postgres:
    image: postgres
    expose:
      - "5432"
    networks:
      - librepass-db
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data:Z

networks:
  librepass-db:
    external: false
